function [fitresult, gof] = createFit(Latency, Bandwidth)
%CREATEFIT(LATENCY,BANDWIDTH)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Latency
%      Y Output: Bandwidth
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Oct-2018 17:06:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Latency, Bandwidth );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [18.8526695915382 -0.275559904885108 2.40334044533282 -0.211132182050173];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'Bandwidth vs. Latency', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel Latency
ylabel Bandwidth
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel Latency
ylabel Bandwidth
grid on


